---
- name: Check if VS Code 'code' command exists
  ansible.builtin.stat:
    path: "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"
  register: vscode_vscode
  tags:
    - vscode

- name: Install VS Code Extension -> {{ item }}
  ansible.builtin.command: "'/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code' --install-extension {{ item }} --force"
  when: vscode_vscode.stat.exists
  changed_when: false
  tags:
    - vscode
