---
- name: Install VS Code (brew cask)
  homebrew_cask:
    name: visual-studio-code
  tags:
  - vscode

- name: Check VS Code Settings Presence
  ansible.builtin.stat:
    path: '{{ ansible_facts["env"]["HOME"] }}/Library/Application Support/Code/User/settings.json'
  register: vscode_settings
  tags:
    - vscode

- name: Ensure VS Code Settings Path
  ansible.builtin.file:
    path: '{{ ansible_facts["env"]["HOME"] }}/Library/Application Support/Code/User'
    state: directory
    recurse: true
  when: not vscode_settings.stat.exists
  tags:
    - vscode

- name: Update VS Code Settings
  ansible.builtin.copy:
    src: settings.json
    dest: '{{ ansible_facts["env"]["HOME"] }}/Library/Application Support/Code/User/settings.json'
    mode: "0644"
  when: not vscode_settings.stat.exists
  tags:
    - vscode

- name: Include vscode_extensions.yml
  ansible.builtin.include_tasks: vscode_extensions.yml
  loop: "{{ vscode_extensions }}"
  tags:
    - vscode
