---
- include_tasks: bazel_darwin.yml
  when: ansible_facts['os_family'] == "Darwin"
  tags:
  - bazel

- include_tasks: bazel_linux.yml
  when: 
  - ansible_facts['machine'] == "x86_64" 
  - ansible_facts['distribution'] == "Debian" or ansible_facts['distribution'] == "Ubuntu"
  tags:
  - bazel

- name: Check .bazelrc Presence
  stat:
    path: "{{ ansible_env.HOME }}/.bazelrc"
  register: bazelrc
  tags:
  - bazel

- name: Create .bazelrc file
  copy:
    src: .bazelrc
    dest: "{{ ansible_env.HOME }}/.bazelrc"
    mode: "0644"
  when: not bazelrc.stat.exists
  tags:
  - bazel