---
- name: Include Bazel Darwin tasks
  ansible.builtin.include_tasks: bazel_darwin.yml
  when: ansible_facts['os_family'] == "Darwin"
  tags:
    - bazel

- name: Include Bazel Linux tasks
  ansible.builtin.include_tasks: bazel_linux.yml
  when:
    - ansible_facts['machine'] == "x86_64"
    - ansible_facts['distribution'] == "Debian" or ansible_facts['distribution'] == "Ubuntu"
  tags:
    - bazel

- name: Check for .bazelrc file
  ansible.builtin.stat:
    path: '{{ ansible_facts["env"]["HOME"] }}/.bazelrc'
  register: bazel_bazelrc
  tags:
    - bazel

- name: Create .bazelrc file if missing
  ansible.builtin.copy:
    src: .bazelrc
    dest: '{{ ansible_facts["env"]["HOME"] }}/.bazelrc'
    mode: "0644"
  when: not bazel_bazelrc.stat.exists
  tags:
    - bazel
