---
brew_python_version: "3.10"
brew_mysql_version: "5.7"
openjdk_version: "17"

brew_taps:
  - sha1n/tap
  - homebrew/cask
  - homebrew/core

brew_formulas: []

macos_brew_formulas:
  - make
  - vim
  - hako
  - bert
  - hyperfine
  - wget
  - watch
  - kubernetes-cli
  - python@{{ brew_python_version }}
  - poetry
  - ansible-lint
  - tree
  - jq
  - gnu-time
  - librdkafka
  - postgresql
  - minikube
  # - mysql@{{ brew_mysql_version }}
  # - mysql-client@{{ brew_mysql_version }}

linux_brew_formulas:
  - gcc

brew_casks:
  - iterm2
  - google-chrome
  - sublime-text
  - intellij-idea-ce
  - pycharm-ce
  - docker
  - slack
  - telegram
  - zoom
  # - google-cloud-sdk
  # - mysqlworkbench
  # - virtualbox
  # - vagrant