---
- include_tasks: install_git_darwin.yml
  when: ansible_facts['os_family'] == "Darwin"
  tags:
  - git

- include_tasks: install_git_ubuntu.yml
  when: 
  - ansible_facts['machine'] == "x86_64"
  - ansible_facts['distribution'] == "Debian" or ansible_facts['distribution'] == "Ubuntu"
  tags:
  - git
  - apt

- name: Install GitHub/Lab client
  include_role:
    name: brew
    tasks_from: install_formula.yml
  vars:
    brew_formulas:
    - gh
    - glab
  tags:
  - git
  - gh
  - glab


- name: Check .gitignore_global presence
  stat:
    path: "{{ ansible_env.HOME }}/.gitignore_global"
  register: gitignore_global
  tags:
  - git

- name: Create .gitignore_global file
  copy:
    src: .gitignore_global
    dest: "{{ ansible_env.HOME }}/.gitignore_global"
    mode: "0644"
  when: not gitignore_global.stat.exists
  tags:
  - git

- name: Check .gitconfig presence
  stat:
    path: "{{ ansible_env.HOME }}/.gitconfig"
  register: gitconfig
  tags:
  - git

- name: Configure git (creates ~/.gitconfig)
  ansible.builtin.template:
    src: .gitconfig.j2
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    mode: "0644"
  when: not gitconfig.stat.exists
  tags:
  - git
