---
- name: Install Git Tools
  include_role:
    name: brew
    tasks_from: install_formula.yml
  when: ansible_facts['os_family'] == "Darwin"
  vars:
    brew_formulas:
    - git
  tags:
  - git
  - gh
