---
- name: Install apt package
  apt:
    pkg: 
      - "{{ item }}"
    update_cache: yes
    state: present
  become: true
  loop: "{{ apt_packages | mandatory }}"
  tags:
  - always

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  become: true
  tags:
  - always
