#!/usr/bin/env ansible-playbook
- hosts: localhost
  connection: local
  
  vars_prompt:
    - name: git_user_name
      default: "{{ default_git_user_name }}"
      private: false
      prompt: Enter your .gitconfig username
    - name: git_user_email
      default: "{{ default_git_user_email }}"
      private: false
      prompt: Enter your .gitconfig email

  roles:
  - shell
  - git
  - brew
  - bazel
  - node
  - go
  - vscode
  
  vars_files:
    - "../vars/user.yml"
    - "../vars/versions.yml"
    - "../vars/dev_apps.yml"
