#!/usr/bin/env ansible-playbook
- hosts: localhost
  connection: local
  
  vars_prompt:
    - name: git_user_email
      private: false
      prompt: Enter your github email address

  roles:
  - brew
  - git

  vars_files:
    - "../vars/user.yml"
    - "../vars/versions.yml"
    - "../vars/essential_apps.yml"
