#!/usr/bin/env ansible-playbook
---
- name: Essentials
  hosts: localhost
  connection: local

  roles:
    - shell
    - brew

  vars_files:
    - "../vars/versions.yml"
    - "../vars/essential_apps.yml"
