---
- name: Install Neovim using Homebrew
  ansible.builtin.include_role:
    name: brew
    tasks_from: install_formula.yml
  vars:
    brew_formulas:
      - nvim
  when:
    - ansible_facts['os_family'] == "Darwin"
  tags:
    - nvim

- name: Check if Neovim init.lua is installed
  ansible.builtin.stat:
    path: '{{ ansible_facts["env"]["HOME"] }}/.config/nvim/init.lua'
  register: shell_kickstart_nvim
  tags:
    - nvim

# WARNING: This git task may not be fully idempotent if the remote changes.
# We accept this risk for this playbook.
- name: Clone kickstart.nvim repository
  ansible.builtin.git:
    repo: git@github.com:sha1n/kickstart.nvim.git
    dest: '{{ ansible_facts["env"]["HOME"] }}/code/kickstart.nvim'
    update: false
  when: shell_kickstart_nvim is defined and not shell_kickstart_nvim.stat.exists
  tags:
    - nvim

- name: Create Neovim config directory
  ansible.builtin.command: 'mkdir -p {{ ansible_facts["env"]["HOME"] }}/.config/nvim/'
  when: shell_kickstart_nvim is defined and not shell_kickstart_nvim.stat.exists
  changed_when: false
  tags:
    - nvim

- name: Install kickstart.nvim init.lua
  ansible.builtin.command: 'ln -s {{ ansible_facts["env"]["HOME"] }}/code/kickstart.nvim/init.lua {{ ansible_facts["env"]["HOME"] }}/.config/nvim/init.lua'
  when: shell_kickstart_nvim is defined and not shell_kickstart_nvim.stat.exists
  changed_when: false
  tags:
    - nvim
