---
- name: Check .path Presence
  stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: omz_home
  tags:
  - omz
  - zsh

# FIXME: figure out how to reuse https://github.com/ctorgalson/ansible-role-oh-my-zsh
- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  register: omz_install
  when: not omz_home.stat.exists
  changed_when: omz_install.rc == 0
  tags:
  - omz
  - zsh

- name: Register OMZ plugins
  replace:
    path: "{{ ansible_env.HOME }}/.zshrc"
    regexp: '^plugins=\(.*\)$'
    replace: |
      plugins=(
        git 
        history-substring-search
      )
  tags:
  - omz
  - zsh

- name: Set OMZ 'agnoster' theme
  replace:
    path: "{{ ansible_env.HOME }}/.zshrc"
    regexp: 'ZSH_THEME="robbyrussell"'
    replace: 'ZSH_THEME="agnoster"'
  tags:
  - omz
  - zsh

- name: Check prompt overridden 
  lineinfile:
    state: absent
    path: "{{ ansible_env.HOME }}/.zshrc"
    regexp: '^prompt_context\(\)\s*\{\s*\}\s*$'
  check_mode: true
  changed_when: false
  register: prompt_override
  tags:
  - omz
  - zsh

- name: Override prompt context
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: |
      # override prompt to remove host name
      prompt_context(){}
    state: present
  when: prompt_override.found == 0
  tags:
  - omz
  - zsh
