---
- name: Check .path Presence
  stat:
    path: "{{ ansible_env.HOME }}/.exports"
  register: paths
  tags:
  - zsh

- name: Create .exports file
  copy:
    src: .exports
    dest: "{{ ansible_env.HOME }}/.exports"
  when: not paths.stat.exists
  tags:
  - zsh

- name: Source .exports file
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: source "$HOME/.exports"
  when: not paths.stat.exists
  tags:
  - zsh
