---
- name: Check if Powerline fonts are installed
  ansible.builtin.find:
    paths: '{{ ansible_facts["env"]["HOME"] }}/Library/Fonts'
    file_type: file
    patterns: ".*Powerline.*.ttf"
    use_regex: true
  when: ansible_facts['os_family'] == "Darwin"
  register: shell_power_line_fonts_installed
  tags:
    - powerline-fonts
    - zsh

# WARNING: This git task may not be fully idempotent if the remote changes.
# We accept this risk for this playbook.
- name: Clone Powerline fonts repository
  ansible.builtin.git:
    repo: git@github.com:powerline/fonts.git
    dest: '{{ ansible_facts["env"]["HOME"] }}/code/fonts'
    update: false
  when: shell_power_line_fonts_installed.files is defined and shell_power_line_fonts_installed.files|length == 0
  tags:
    - powerline-fonts
    - zsh

- name: Install Powerline fonts
  ansible.builtin.command: '{{ ansible_facts["env"]["HOME"] }}/code/fonts/install.sh'
  when: shell_power_line_fonts_installed.files is defined and shell_power_line_fonts_installed.files|length == 0
  changed_when: false
  tags:
    - powerline-fonts
    - zsh
