---
- name: Check if profile repository is installed
  ansible.builtin.find:
    paths:
      - '{{ ansible_facts["env"]["HOME"] }}/code/profile'
    file_type: file
    patterns: ".include"
  register: shell_profile_repo_installed
  tags:
    - profile
    - zsh

# WARNING: This git task may not be fully idempotent if the remote changes.
# We accept this risk for this playbook.
- name: Clone profile repository
  ansible.builtin.git:
    repo: git@github.com:sha1n/profile.git
    dest: '{{ ansible_facts["env"]["HOME"] }}/code/profile'
    update: false
  when: shell_profile_repo_installed.files is defined and shell_profile_repo_installed.files|length == 0
  tags:
    - profile
    - zsh

- name: Install coreutils
  ansible.builtin.include_role:
    name: brew
    tasks_from: install_formula.yml
  vars:
    brew_formulas:
      - coreutils
  when: ansible_facts['os_family'] == "Darwin"
  tags:
    - profile
    - zsh

- name: Install profile
  ansible.builtin.command: '{{ ansible_facts["env"]["HOME"] }}/code/profile/install.sh'
  when: shell_profile_repo_installed.files is defined and shell_profile_repo_installed.files|length == 0
  changed_when: false
  tags:
    - profile
    - zsh
