---
- name: Check if Solarized Vim colors are installed
  ansible.builtin.stat:
    path: '{{ ansible_facts["env"]["HOME"] }}/.vim/colors/solarized.vim'
  register: shell_solarized_vim
  tags:
    - vim

# WARNING: This git task may not be fully idempotent if the remote changes.
# We accept this risk for this playbook.
- name: Clone vim-colors-solarized repository
  ansible.builtin.git:
    repo: git@github.com:altercation/vim-colors-solarized.git
    dest: '{{ ansible_facts["env"]["HOME"] }}/code/vim-colors-solarized'
    update: false
  when: shell_solarized_vim is defined and not shell_solarized_vim.stat.exists
  tags:
    - vim

- name: Create Vim colors directory
  ansible.builtin.command: 'mkdir -p {{ ansible_facts["env"]["HOME"] }}/.vim/colors'
  when: shell_solarized_vim is defined and not shell_solarized_vim.stat.exists
  changed_when: false
  tags:
    - vim
- name: Install Solarized Vim color scheme
  ansible.builtin.command: 'cp {{ ansible_facts["env"]["HOME"] }}/code/vim-colors-solarized/colors/solarized.vim {{ ansible_facts["env"]["HOME"] }}/.vim/colors'
  when: shell_solarized_vim is defined and not shell_solarized_vim.stat.exists
  changed_when: false
  tags:
    - vim
