---
- name: Install Zsh
  ansible.builtin.command: apt install -y zsh
  register: shell_zsh_installed
  become: true
  changed_when: shell_zsh_installed.rc == 0
  tags:
    - zsh

- name: Change Shell to Zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  tags:
    - zsh
